class DummyData {
  var items = <String>[
    'food.png',
    'groceries.png',
    'groceries (1).png',
    'groceries (2).png',
    'grocery.png',
    'basket.png',
    'shopping-bag.png',
    'shopping-bag (2).png',
    'groceries (1).png',
    'grocery.png',
    'basket.png',
    'groceries (2).png',
    'food.png',
    'groceries.png',
    'shopping-bag (2).png',
    'shopping-bag.png',
    'food.png',
    'groceries.png',
    'groceries (1).png',
    'groceries (2).png',
    'grocery.png',
    'basket.png',
    'shopping-bag.png',
    'shopping-bag (2).png',
    'groceries (1).png',
    'grocery.png',
    'basket.png',
    'groceries (2).png',
    'food.png',
    'groceries.png',
    'shopping-bag (2).png',
    'shopping-bag.png',
    'food.png',
    'groceries.png',
    'groceries (1).png',
    'groceries (2).png',
    'grocery.png',
    'basket.png',
    'shopping-bag.png',
    'shopping-bag (2).png',
    'groceries (1).png',
    'grocery.png',
    'basket.png',
    'groceries (2).png',
    'food.png',
    'groceries.png',
    'shopping-bag (2).png',
    'shopping-bag.png',
    'food.png',
    'groceries.png',
    'groceries (1).png',
    'groceries (2).png',
    'grocery.png',
    'basket.png',
    'shopping-bag.png',
    'shopping-bag (2).png',
    'groceries (1).png',
    'grocery.png',
    'basket.png',
    'groceries (2).png',
    'food.png',
    'groceries.png',
    'shopping-bag (2).png',
    'shopping-bag.png',
  ];

  var countries = <Map<String, dynamic>>[
    {"code": "93", "name": "Afghanistan", "abbreviation": "AF"},
    {"code": "213", "name": "Algeria", "abbreviation": "DZ"},
    {"code": "244", "name": "Angola", "abbreviation": "AO"},
    {"code": "1-264", "name": "Anguilla", "abbreviation": "AI"},
    {"code": "672", "name": "Antarctica", "abbreviation": "AQ"},
    {"code": "54", "name": "Argentina", "abbreviation": "AR"},
    {"code": "374", "name": "Armenia", "abbreviation": "AM"},
    {"code": "61", "name": "Australia", "abbreviation": "AU"},
    {"code": "43", "name": "Austria", "abbreviation": "AT"},
    {"code": "973", "name": "Bahrain", "abbreviation": "BH"},
    {"code": "880", "name": "Bangladesh", "abbreviation": "BD"},
    {"code": "229", "name": "Benin", "abbreviation": "BJ"},
    {"code": "1-441", "name": "Bermuda", "abbreviation": "BM"},
    {"code": "975", "name": "Bhutan", "abbreviation": "BT"},
    {"code": "591", "name": "Bolivia", "abbreviation": "BO"},
    {"code": "387", "name": "Bosnia and Herzegovina", "abbreviation": "BA"},
    {"code": "267", "name": "Botswana", "abbreviation": "BW"},
    {"code": "55", "name": "Brazil", "abbreviation": "BR"},
    {"code": "1-284", "name": "British Virgin Islands", "abbreviation": "VG"},
    {"code": "673", "name": "Brunei", "abbreviation": "BN"},
    {"code": "359", "name": "Bulgaria", "abbreviation": "BG"},
    {"code": "226", "name": "Burkina Faso", "abbreviation": "BF"},
    {"code": "257", "name": "Burundi", "abbreviation": "BI"},
    {"code": "237", "name": "Cameroon", "abbreviation": "CM"},
    {"code": "1", "name": "Canada", "abbreviation": "CA"},
    {"code": "236", "name": "Central African Republic", "abbreviation": "CF"},
    {"code": "86", "name": "China", "abbreviation": "CN"},
    {"code": "57", "name": "Colombia", "abbreviation": "CO"},
    {"code": "506", "name": "Costa Rica", "abbreviation": "CR"},
    {"code": "385", "name": "Croatia", "abbreviation": "HR"},
    {"code": "53", "name": "Cuba", "abbreviation": "CU"},
    {"code": "45", "name": "Denmark", "abbreviation": "DK"},
    {"code": "593", "name": "Ecuador", "abbreviation": "EC"},
    {"code": "20", "name": "Egypt", "abbreviation": "EG"},
    {"code": "503", "name": "El Salvador", "abbreviation": "SV"},
    {"code": "251", "name": "Ethiopia", "abbreviation": "ET"},
    {"code": "33", "name": "France", "abbreviation": "FR"},
    {"code": "241", "name": "Gabon", "abbreviation": "GA"},
    {"code": "995", "name": "Georgia", "abbreviation": "GE"},
    {"code": "49", "name": "Germany", "abbreviation": "DE"},
    {"code": "233", "name": "Ghana", "abbreviation": "GH"},
    {"code": "44-1481", "name": "Guernsey", "abbreviation": "GG"},
    {"code": "224", "name": "Guinea", "abbreviation": "GN"},
    {"code": "245", "name": "Guinea-Bissau", "abbreviation": "GW"},
    {"code": "852", "name": "Hong Kong", "abbreviation": "HK"},
    {"code": "354", "name": "Iceland", "abbreviation": "IS"},
    {"code": "91", "name": "India", "abbreviation": "IN"},
    {"code": "62", "name": "Indonesia", "abbreviation": "ID"},
    {"code": "98", "name": "Iran", "abbreviation": "IR"},
    {"code": "964", "name": "Iraq", "abbreviation": "IQ"},
    {"code": "353", "name": "Ireland", "abbreviation": "IE"},
    {"code": "39", "name": "Italy", "abbreviation": "IT"},
    {"code": "81", "name": "Japan", "abbreviation": "JP"},
    {"code": "962", "name": "Jordan", "abbreviation": "JO"},
    {"code": "7", "name": "Kazakhstan", "abbreviation": "KZ"},
    {"code": "254", "name": "Kenya", "abbreviation": "KE"},
    {"code": "965", "name": "Kuwait", "abbreviation": "KW"},
    {"code": "961", "name": "Lebanon", "abbreviation": "LB"},
    {"code": "218", "name": "Libya", "abbreviation": "LY"},
    {"code": "352", "name": "Luxembourg", "abbreviation": "LU"},
    {"code": "389", "name": "Macedonia", "abbreviation": "MK"},
    {"code": "261", "name": "Madagascar", "abbreviation": "MG"},
    {"code": "265", "name": "Malawi", "abbreviation": "MW"},
    {"code": "960", "name": "Maldives", "abbreviation": "MV"},
    {"code": "223", "name": "Mali", "abbreviation": "ML"},
    {"code": "356", "name": "Malta", "abbreviation": "MT"},
    {"code": "52", "name": "Mexico", "abbreviation": "MX"},
    {"code": "976", "name": "Mongolia", "abbreviation": "MN"},
    {"code": "212", "name": "Morocco", "abbreviation": "MA"},
    {"code": "258", "name": "Mozambique", "abbreviation": "MZ"},
    {"code": "95", "name": "Myanmar", "abbreviation": "MM"},
    {"code": "264", "name": "Namibia", "abbreviation": "NA"},
    {"code": "977", "name": "Nepal", "abbreviation": "NP"},
    {"code": "31", "name": "Netherlands", "abbreviation": "NL"},
    {"code": "64", "name": "New Zealand", "abbreviation": "NZ"},
    {"code": "227", "name": "Niger", "abbreviation": "NE"},
    {"code": "234", "name": "Nigeria", "abbreviation": "NG"},
    {"code": "850", "name": "North Korea", "abbreviation": "KP"},
    {"code": "968", "name": "Oman", "abbreviation": "OM"},
    {"code": "92", "name": "Pakistan", "abbreviation": "PK"},
    {"code": "970", "name": "Palestine", "abbreviation": "PS"},
    {"code": "507", "name": "Panama", "abbreviation": "PA"},
    {"code": "595", "name": "Paraguay", "abbreviation": "PY"},
    {"code": "63", "name": "Philippines", "abbreviation": "PH"},
    {"code": "48", "name": "Poland", "abbreviation": "PL"},
    {"code": "351", "name": "Portugal", "abbreviation": "PT"},
    {"code": "974", "name": "Qatar", "abbreviation": "QA"},
    {"code": "40", "name": "Romania", "abbreviation": "RO"},
    {"code": "7", "name": "Russia", "abbreviation": "RU"},
    {"code": "250", "name": "Rwanda", "abbreviation": "RW"},
    {"code": "966", "name": "Saudi Arabia", "abbreviation": "SA"},
    {"code": "221", "name": "Senegal", "abbreviation": "SN"},
    {"code": "381", "name": "Serbia", "abbreviation": "RS"},
    {"code": "421", "name": "Slovakia", "abbreviation": "SK"},
    {"code": "386", "name": "Slovenia", "abbreviation": "SI"},
    {"code": "252", "name": "Somalia", "abbreviation": "SO"},
    {"code": "27", "name": "South Africa", "abbreviation": "ZA"},
    {"code": "82", "name": "South Korea", "abbreviation": "KR"},
    {"code": "211", "name": "South Sudan", "abbreviation": "SS"},
    {"code": "34", "name": "Spain", "abbreviation": "ES"},
    {"code": "249", "name": "Sudan", "abbreviation": "SD"},
    {"code": "46", "name": "Sweden", "abbreviation": "SE"},
    {"code": "963", "name": "Syria", "abbreviation": "SY"},
    {"code": "886", "name": "Taiwan", "abbreviation": "TW"},
    {"code": "992", "name": "Tajikistan", "abbreviation": "TJ"},
    {"code": "255", "name": "Tanzania", "abbreviation": "TZ"},
    {"code": "228", "name": "Togo", "abbreviation": "TG"},
    {"code": "690", "name": "Tokelau", "abbreviation": "TK"},
    {"code": "676", "name": "Tonga", "abbreviation": "TO"},
    {"code": "216", "name": "Tunisia", "abbreviation": "TN"},
    {"code": "90", "name": "Turkey", "abbreviation": "TR"},
    {"code": "993", "name": "Turkmenistan", "abbreviation": "TM"},
    {"code": "1", "name": "United States", "abbreviation": "US"},
  ];
}
